name: CI Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Instalar dependencias necesarias para Chrome en Linux
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
          sudo apt-get install -y google-chrome-stable

      # 4. Instalar Allure CLI
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -xzf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # 5. Ejecutar pruebas con Maven
      - name: Run tests
        continue-on-error: true
        run: |
          cd selenium-ui
          mvn clean test --fail-never

      # 6. Generar el reporte de Allure
      - name: Generate Allure Report
        run: |
          allure generate --clean selenium-ui/target/allure-results -o docs

      # 7. Commit y push directo a la rama `master`
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add docs
          git commit -m "Deploy Allure Report to GitHub Pages" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
