name: CI Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Cachear dependencias de Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Instalar dependencias necesarias para Chrome en Linux
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
          sudo apt-get install -y google-chrome-stable

      # 5. Instalar Allure CLI
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          tar -xzf allure-2.21.0.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # 6. Ejecutar pruebas con Maven dentro del directorio correcto
      - name: Run tests
        continue-on-error: true  # Continúa incluso si las pruebas fallan
        run: |
          cd selenium-ui
          mvn clean test --fail-never

      # 7. Generar Reporte HTML de Allure
      - name: Generate Allure Report
        run: |
          allure generate --clean selenium-ui/target/allure-results -o selenium-ui/target/allure-report

      # # 8. Mover el reporte generado al directorio raíz del repositorio
      # - name: Move Allure Report to Root
      #   run: |
      #     cp -r selenium-ui/target/allure-report/* .

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Deploy Allure Report to GitHub Pages" || echo "No changes to commit"
          git push
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}